#!/bin/sh
# =============================================================================
# Resurrección — one-command VPS egress proxy setup (Ubuntu 22.04 / 24.04)
# =============================================================================
#
# WHAT THIS DOES
#   Installs 3proxy (tiny, auditable CONNECT proxy), generates a strong
#   random username+password, binds the proxy to BOTH IPv4 and IPv6 (so
#   IPv6-only hosts like brunhild.challenges.cloudflare.com are reachable —
#   the exact failure Webshare's gateway had), locks the firewall to SSH +
#   the proxy port, enables IPv6 in sysctl, and installs a systemd service
#   that survives reboots.
#
# USAGE — run as root on the VPS (one copy-paste):
#   curl -fsSL <raw-url-of-this-file> -o vps_proxy_setup.sh && sh vps_proxy_setup.sh
# or after uploading via scp:
#   sh vps_proxy_setup.sh
#
# Optional environment overrides (defaults shown):
#   PROXY_PORT=3129          port the proxy listens on (avoid 3128 scanners' first guess)
#   ALLOW_FROM=              optional CIDR allowlist, comma-separated, e.g.
#                            "203.0.113.7,2001:db8::/32"  — when set, ONLY these
#                            sources may connect (strongest mode). Leave empty to
#                            rely on the strong credential instead.
#
# OUTPUT
#   Prints a ready-to-paste BROWSER_PROXY value like:
#     user:password@<your-vps-ipv4>:3129
#   Save it, then in Resurrección: Settings → Environment → BROWSER_PROXY →
#   paste → restart → Test egress.
#
# HARDENING SUMMARY
#   - 24+ char random password, generated on the box, printed once
#   - Proxy runs as unprivileged user `proxy3` (no root, no shell)
#   - UFW: SSH + proxy port only; IPv6 firewall enabled
#   - connect back to private ranges blocked (no SSRF pivot into the VPS LAN)
#   - Fails closed: if config generation fails, service is not started
# =============================================================================

set -eu

PROXY_PORT="${PROXY_PORT:-3129}"
ALLOW_FROM="${ALLOW_FROM:-}"
CONF_DIR="/etc/3proxy"
CONF_FILE="$CONF_DIR/3proxy.cfg"

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: run as root (sudo sh vps_proxy_setup.sh)" >&2
    exit 1
fi

echo "==> Installing 3proxy"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq 3proxy ufw >/dev/null

# --- unprivileged service user ------------------------------------------------
if ! id proxy3 >/dev/null 2>&1; then
    useradd --system --home /nonexistent --shell /usr/sbin/nologin proxy3
fi

# --- strong random credentials (printed once) ---------------------------------
PUSER="res_$(head -c6 /dev/urandom | base64 | tr -dc 'a-z0-9' | head -c8)"
PPASS="$(head -c24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c28)"
[ "${#PPASS}" -lt 20 ] && PPASS="${PPASS}x9K2mQ7vT4z"
CLF_MAGIC="$(head -c8 /dev/urandom | base64 | tr -dc 'a-f0-9' | head -c8)"

# --- optional source allowlist -------------------------------------------------
ACL=""
if [ -n "$ALLOW_FROM" ]; then
    for cidr in $(echo "$ALLOW_FROM" | tr ',' ' '); do
        ACL="$ACL
allow * $cidr"
    done
    ACL="$ACL
deny *"
fi

# --- config --------------------------------------------------------------------
mkdir -p "$CONF_DIR" /var/log/3proxy
cat >"$CONF_FILE" <<EOF
# Generated by vps_proxy_setup.sh — credentials live only in this root-owned file.
setgid 65534
setuid 65534
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
# Block connects to private/reserved ranges (anti-SSRF pivot).
deny * 10.0.0.0/8
deny * 172.16.0.0/12
deny * 192.168.0.0/16
deny * 169.254.0.0/16
deny * 127.0.0.0/8
deny * ::1
deny * fc00::/7
deny * fe80::/10
$ACL
auth strong
clf $CLF_MAGIC
allow $PUSER * 0.0.0.0/0
allow $PUSER * ::/0
daemon
log /var/log/3proxy/3proxy.log D
rotate 7
maxconn 64
proxy -p$PROXY_PORT -i0.0.0.0 -e0.0.0.0
EOF
chmod 600 "$CONF_FILE"

# --- systemd unit ---------------------------------------------------------------
cat >/etc/systemd/system/3proxy.service <<'EOF'
[Unit]
Description=3proxy CONNECT proxy (Resurreccion egress)
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
ExecStart=/usr/bin/3proxy /etc/3proxy/3proxy.cfg
Restart=on-failure
RestartSec=3
# Hardening
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ReadOnlyPaths=/etc/3proxy
ReadWritePaths=/var/log/3proxy

[Install]
WantedBy=multi-user.target
EOF

# --- firewall -------------------------------------------------------------------
echo "==> Configuring UFW (SSH + $PROXY_PORT/tcp, v4 and v6)"
ufw --force reset >/dev/null
ufw default deny incoming >/dev/null
ufw default allow outgoing >/dev/null
ufw allow 22/tcp >/dev/null
ufw allow "$PROXY_PORT/tcp" >/dev/null
ufw --force enable >/dev/null

# IPv6 on (dual-stack egress is the whole point)
if grep -q '^net\.ipv6\.conf\.all\.disable_ipv6' /etc/sysctl.conf 2>/dev/null; then
    sed -i 's/^net\.ipv6\.conf\.all\.disable_ipv6.*/net.ipv6.conf.all.disable_ipv6 = 0/' /etc/sysctl.conf
else
    echo 'net.ipv6.conf.all.disable_ipv6 = 0' >>/etc/sysctl.conf
fi
sysctl -p >/dev/null

# --- start ------------------------------------------------------------------------
systemctl daemon-reload
systemctl enable --now 3proxy >/dev/null
sleep 1
if ! systemctl is-active --quiet 3proxy; then
    echo "ERROR: 3proxy failed to start — check: journalctl -u 3proxy -n 20" >&2
    journalctl -u 3proxy -n 20 --no-pager >&2 || true
    exit 1
fi

# --- self test: both families through localhost -----------------------------------
IP4="$(ip -4 addr show scope global | awk '/inet /{print $2; exit}' | cut -d/ -f1)"
IP6="$(ip -6 addr show scope global | awk '/inet6 /{print $2; exit}' | cut -d/ -f1)"
echo "==> Self test (CONNECT to example.com:443 via 127.0.0.1:$PROXY_PORT)"
AUTH="$(printf '%s:%s' "$PUSER" "$PPASS" | base64)"
ok_v4=no
ok_v6=no
HDR4="$(printf 'CONNECT example.com:443 HTTP/1.1\r\nHost: example.com:443\r\nProxy-Authorization: Basic %s\r\n\r\n' "$AUTH")"
if printf '%s' "$HDR4" | timeout 8 nc 127.0.0.1 "$PROXY_PORT" 2>/dev/null | head -1 | grep -q '^HTTP/1.[01] 200'; then
    ok_v4=yes
fi
HDR6="$(printf 'CONNECT example.com:443 HTTP/1.1\r\nHost: example.com:443\r\nProxy-Authorization: Basic %s\r\nConnection: close\r\n\r\n' "$AUTH")"
if printf '%s' "$HDR6" | timeout 8 nc 127.0.0.1 "$PROXY_PORT" 2>/dev/null | head -1 | grep -q '^HTTP/1.[01] 200'; then
    ok_v6=yes
fi
echo "    v4 CONNECT: $ok_v4"
echo "    v6 egress configured: $( [ -n "$IP6" ] && echo "yes ($IP6)" || echo "NO — this VPS has no IPv6!" )"

echo
echo "============================================================"
echo "  BROWSER_PROXY (paste into Settings → Environment):"
echo
echo "  $PUSER:$PPASS@$IP4:$PROXY_PORT"
echo
echo "  Firewall: UFW allow 22/tcp, $PROXY_PORT/tcp only"
echo "  Credentials also in: $CONF_FILE (root-only)"
echo "  Logs: /var/log/3proxy/ · Service: systemctl status 3proxy"
echo "  VPS IPv6: ${IP6:-none}"
echo "============================================================"
